version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@x.y # Use the Heroku orb in your config


jobs:
  build:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build app
          command: npm run build

  test:
    docker:
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Test app
          command: npm test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
  heroku_deploy:
     jobs:
       - build
       - heroku/deploy-via-git:
           requires:
             - build # only run deploy-via-git job if the build job has completed
           filters:
             branches:
               only: master # only run deploy-via-git job on main branch
